version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: dev_mysql8
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: app_pass_123
      MYSQL_ROOT_PASSWORD: root_pass_123
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -uappuser -papp_pass_123 --silent",
        ]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "3307:3306"
    networks: [devnet]
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:16-alpine
    container_name: dev_postgres16
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: app_pass_123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "5433:5432"
    networks: [devnet]
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: dev_adminer
    depends_on:
      mysql:
        condition: service_healthy
      postgres:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    networks: [devnet]

  backend:
    build:
      context: ../BACKEND
      dockerfile: Dockerfile
    container_name: dev_backend
    command: ["sleep", "infinity"]
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql+pymysql://appuser:app_pass_123@mysql:3306/appdb
      # DATABASE_URL: postgresql+psycopg://appuser:app_pass_123@postgres:5432/appdb
    volumes:
      - ..:/workspaces:cached
    networks: [devnet]
    depends_on:
      mysql:
        condition: service_healthy
      postgres:
        condition: service_started

networks:
  devnet:
    driver: bridge

volumes:
  mysql_data:
  pg_data:
